/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	nonnativeresourcev1alpha1 "k8s.io/non-native-resource-api/pkg/apis/non.native.resource/v1alpha1"
	versioned "k8s.io/non-native-resource-api/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/non-native-resource-api/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/non-native-resource-api/pkg/client/listers/non.native.resource/v1alpha1"
)

// RefinedNodeResourceInformer provides access to a shared informer and lister for
// RefinedNodeResources.
type RefinedNodeResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RefinedNodeResourceLister
}

type refinedNodeResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewRefinedNodeResourceInformer constructs a new informer for RefinedNodeResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRefinedNodeResourceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRefinedNodeResourceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredRefinedNodeResourceInformer constructs a new informer for RefinedNodeResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRefinedNodeResourceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NonV1alpha1().RefinedNodeResources().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NonV1alpha1().RefinedNodeResources().Watch(context.TODO(), options)
			},
		},
		&nonnativeresourcev1alpha1.RefinedNodeResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *refinedNodeResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRefinedNodeResourceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *refinedNodeResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&nonnativeresourcev1alpha1.RefinedNodeResource{}, f.defaultInformer)
}

func (f *refinedNodeResourceInformer) Lister() v1alpha1.RefinedNodeResourceLister {
	return v1alpha1.NewRefinedNodeResourceLister(f.Informer().GetIndexer())
}
